const currencies =
[
  { value: 'AFN', label: 'Afghan Afghani (AFN)' },
  { value: 'ALL', label: 'Albanian Lek (ALL)' },
  { value: 'DZD', label: 'Algerian Dinar (DZD)' },
  { value: 'AOA', label: 'Angolan Kwanza (AOA)' },
  { value: 'ARS', label: 'Argentine Peso (ARS)' },
  { value: 'AMD', label: 'Armenian Dram (AMD)' },
  { value: 'AWG', label: 'Aruban Florin (AWG)' },
  { value: 'AUD', label: 'Australian Dollar (AUD)' },
  { value: 'AZN', label: 'Azerbaijan Manat (AZN)' },
  { value: 'BSD', label: 'Bahamian Dollar (BSD)' },
  { value: 'BHD', label: 'Bahraini Dinar (BHD)' },
  { value: 'BDT', label: 'Bangladeshi Taka (BDT)' },
  { value: 'BBD', label: 'Barbados Dollar (BBD)' },
  { value: 'BAM', label: 'Bosnia & Herzegovina Convertible Mark (BAM)' },
  { value: 'BYN', label: 'Belarusian Ruble (BYN)' },
  { value: 'BZD', label: 'Belize Dollar (BZD)' },
  { value: 'BMD', label: 'Bermudian Dollar (BMD)' },
  { value: 'BTN', label: 'Bhutanese Ngultrum (BTN)' },
  { value: 'VES', label: 'Bolívar Soberano (VES)' },
  { value: 'BOB', label: 'Bolivian Boliviano (BOB)' },
  { value: 'BWP', label: 'Botswana Pula (BWP)' },
  { value: 'BRL', label: 'Brazilian Real (BRL)' },
  { value: 'BND', label: 'Brunei Dollar (BND)' },
  { value: 'BGN', label: 'Bulgarian Lev (BGN)' },
  { value: 'MMK', label: 'Burmese Kyat (MMK)' },
  { value: 'BIF', label: 'Burundi Franc (BIF)' },
  { value: 'CVE', label: 'Cabo Verde Escudo (CVE)' },
  { value: 'KHR', label: 'Cambodian Riel (KHR)' },
  { value: 'CAD', label: 'Canadian Dollar (CAD)' },
  { value: 'KYD', label: 'Cayman Islands Dollar (KYD)' },
  { value: 'XOF', label: 'CFA Franc BCEAO (XOF)' },
  { value: 'XAF', label: 'CFA Franc BEAC (XAF)' },
  { value: 'XPF', label: 'CFP Franc (XPF)' },
  { value: 'CLP', label: 'Chilean Peso (CLP)' },
  { value: 'CNY', label: 'Chinese Yuan Renminbi (CNY)' },
  { value: 'COP', label: 'Colombian Peso (COP)' },
  { value: 'KMF', label: 'Comorian Franc  (KMF)' },
  { value: 'CDF', label: 'Congolese Franc (CDF)' },
  { value: 'CRC', label: 'Costa Rican Colon (CRC)' },
  { value: 'HRK', label: 'Croatian Kuna (HRK)' },
  { value: 'CUP', label: 'Cuban Peso (CUP)' },
  { value: 'CZK', label: 'Czech Koruna (CZK)' },
  { value: 'DKK', label: 'Danish Krone (DKK)' },
  { value: 'DJF', label: 'Djibouti Franc (DJF)' },
  { value: 'DOP', label: 'Dominican Peso (DOP)' },
  { value: 'XCD', label: 'East Caribbean Dollar (XCD)' },
  { value: 'EGP', label: 'Egyptian Pound (EGP)' },
  { value: 'SVC', label: 'El Salvador Colon (SVC)' },
  { value: 'ERN', label: 'Eritrean Nakfa (ERN)' },
  { value: 'ETB', label: 'Ethiopian Birr (ETB)' },
  { value: 'EUR', label: 'Europeon Union Euro (EUR)' },
  { value: 'FKP', label: 'Falkland Islands Pound (FKP)' },
  { value: 'FJD', label: 'Fiji Dollar (FJD)' },
  { value: 'GMD', label: 'Gambian Dalasi (GMD)' },
  { value: 'GEL', label: 'Georgian Lari (GEL)' },
  { value: 'GHS', label: 'Ghana Cedi (GHS)' },
  { value: 'GIP', label: 'Gibraltar Pound (GIP)' },
  { value: 'GTQ', label: 'Guatemalan Quetzal (GTQ)' },
  { value: 'GNF', label: 'Guinean Franc (GNF)' },
  { value: 'GYD', label: 'Guyana Dollar (GYD)' },
  { value: 'HTG', label: 'Haitian Gourde (HTG)' },
  { value: 'HNL', label: 'Honduran Lempira (HNL)' },
  { value: 'HKD', label: 'Hong Kong Dollar (HKD)' },
  { value: 'HUF', label: 'Hungarian Forint (HUF)' },
  { value: 'ISK', label: 'Iceland Krona (ISK)' },
  { value: 'INR', label: 'Indian Rupee (INR)' },
  { value: 'IDR', label: 'Indonesian Rupiah (IDR)' },
  { value: 'IRR', label: 'Iranian Rial (IRR)' },
  { value: 'IQD', label: 'Iraqi Dinar (IQD)' },
  { value: 'ILS', label: 'Israeli New Sheqel (ILS)' },
  { value: 'JMD', label: 'Jamaican Dollar (JMD)' },
  { value: 'JPY', label: 'Japanese Yen (JPY)' },
  { value: 'JOD', label: 'Jordanian Dinar (JOD)' },
  { value: 'KZT', label: 'Kazakhstani Tenge (KZT)' },
  { value: 'KES', label: 'Kenyan Shilling (KES)' },
  { value: 'KRW', label: 'Korean Won (KRW)' },
  { value: 'KWD', label: 'Kuwaiti Dinar (KWD)' },
  { value: 'KGS', label: 'Kyrgyzstani Som (KGS)' },
  { value: 'LAK', label: 'Lao Kip (LAK)' },
  { value: 'LBP', label: 'Lebanese Pound (LBP)' },
  { value: 'LSL', label: 'Lesotho Loti (LSL)' },
  { value: 'LRD', label: 'Liberian Dollar (LRD)' },
  { value: 'LYD', label: 'Libyan Dinar (LYD)' },
  { value: 'MOP', label: 'Macanese Pataca (MOP)' },
  { value: 'MKD', label: 'Macedonian Denar (MKD)' },
  { value: 'MGA', label: 'Malagasy Ariary (MGA)' },
  { value: 'MWK', label: 'Malawi Kwacha (MWK)' },
  { value: 'MYR', label: 'Malaysian Ringgit (MYR)' },
  { value: 'MVR', label: 'Maldivian Rufiyaa (MVR)' },
  { value: 'MRU', label: 'Mauritanian Ouguiya (MRU)' },
  { value: 'MUR', label: 'Mauritius Rupee (MUR)' },
  { value: 'MXN', label: 'Mexican Peso (MXN)' },
  { value: 'MDL', label: 'Moldovan Leu (MDL)' },
  { value: 'MNT', label: 'Mongolian Tugrik (MNT)' },
  { value: 'MAD', label: 'Moroccan Dirham (MAD)' },
  { value: 'MZN', label: 'Mozambique Metical (MZN)' },
  { value: 'NAD', label: 'Namibia Dollar (NAD)' },
  { value: 'NPR', label: 'Nepalese Rupee (NPR)' },
  { value: 'ANG', label: 'Netherlands Antillean Guilder (ANG)' },
  { value: 'TWD', label: 'New Taiwan Dollar (TWD)' },
  { value: 'NZD', label: 'New Zealand Dollar (NZD)' },
  { value: 'NIO', label: 'Nicaraguan córdoba (NIO)' },
  { value: 'NGN', label: 'Nigerian Naira (NGN)' },
  { value: 'KPW', label: 'North Korean Won (KPW)' },
  { value: 'NOK', label: 'Norwegian Krone (NOK)' },
  { value: 'PKR', label: 'Pakistan Rupee (PKR)' },
  { value: 'PAB', label: 'Panamanian Balboa (PAB)' },
  { value: 'PGK', label: 'Papua New Guinean Kina (PGK)' },
  { value: 'PYG', label: 'Paraguayan Guarani (PYG)' },
  { value: 'PEN', label: 'Peruvian Sol (PEN)' },
  { value: 'UYU', label: 'Peso Uruguayo (UYU)' },
  { value: 'PHP', label: 'Philippine Peso (PHP)' },
  { value: 'PLN', label: 'Polish Zloty (PLN)' },
  { value: 'QAR', label: 'Qatari Rial (QAR)' },
  { value: 'OMR', label: 'Rial Omani (OMR)' },
  { value: 'RON', label: 'Romanian Leu (RON)' },
  { value: 'RUB', label: 'Russian Ruble (RUB)' },
  { value: 'RWF', label: 'Rwanda Franc (RWF)' },
  { value: 'SHP', label: 'Saint Helena Pound (SHP)' },
  { value: 'WST', label: 'Samoan Tala (WST)' },
  { value: 'STN', label: 'São Tomé and Príncipe Dobra (STN)' },
  { value: 'SAR', label: 'Saudi Riyal (SAR)' },
  { value: 'RSD', label: 'Serbian Dinar (RSD)' },
  { value: 'SCR', label: 'Seychelles Rupee (SCR)' },
  { value: 'SLL', label: 'Sierra Leonean Leone (SLL)' },
  { value: 'SGD', label: 'Singapore Dollar (SGD)' },
  { value: 'SBD', label: 'Solomon Islands Dollar (SBD)' },
  { value: 'SOS', label: 'Somali Shilling (SOS)' },
  { value: 'ZAR', label: 'South African Rand (ZAR)' },
  { value: 'SSP', label: 'South Sudanese Pound (SSP)' },
  { value: 'LKR', label: 'Sri Lanka Rupee (LKR)' },
  { value: 'SDG', label: 'Sudanese Pound (SDG)' },
  { value: 'SRD', label: 'Surinam Dollar (SRD)' },
  { value: 'SZL', label: 'Swazi Lilangeni (SZL)' },
  { value: 'SEK', label: 'Swedish Krona (SEK)' },
  { value: 'CHF', label: 'Swiss Franc (CHF)' },
  { value: 'SYP', label: 'Syrian Pound (SYP)' },
  { value: 'TJS', label: 'Tajikistani Somoni (TJS)' },
  { value: 'TZS', label: 'Tanzanian Shilling (TZS)' },
  { value: 'THB', label: 'Thai Baht (THB)' },
  { value: 'TOP', label: 'Tongan Pa’anga (TOP)' },
  { value: 'TTD', label: 'Trinidad and Tobago Dollar (TTD)' },
  { value: 'TND', label: 'Tunisian Dinar (TND)' },
  { value: 'TRY', label: 'Turkish Lira (TRY)' },
  { value: 'TMT', label: 'Turkmenistan New Manat (TMT)' },
  { value: 'AED', label: 'UAE Dirham (AED)' },
  { value: 'UGX', label: 'Uganda Shilling (UGX)' },
  { value: 'GBP', label: 'UK Pound Sterling (GBP)' },
  { value: 'UAH', label: 'Ukrainian Hryvnia (UAH)' },
  { value: 'USD', label: 'US Dollar (USD)' },
  { value: 'UZS', label: 'Uzbekistan Sum (UZS)' },
  { value: 'VUV', label: 'Vanuatu Vatu (VUV)' },
  { value: 'VND', label: 'Vietnamese Dong (VND)' },
  { value: 'YER', label: 'Yemeni Rial (YER)' },
  { value: 'ZMW', label: 'Zambian Kwacha (ZMW)' },
  { value: 'ZWL', label: 'Zimbabwe Dollar (ZWL)' }
];

export default currencies;
